### ISSUE TITLE
ZIM download experience is terrible

### ISSUE THREAD

**Issue by rgaudin** [kiwix/apple#634] opened 2024-01-22 17:08 UTC
I don't know if it has ever worked properly but I am testing this with macOS nightly.

Downloading a ZIM from the in-app catalog is very difficult and frustrating

- In _Categories_ view, selecting a ZIM and clicking _Download_ has no visual feedback. Button is still there, unchanged.
- Going to _Downloads_ view, there's usually nothing. If I clicked many times at previous step, sometimes I get an entry in _Downloads_ view.
- Progress bar in _Downloads_ view is never updated.
- Going back and forth in _Opened_/_Downloads_ view, I can figure out if download completed (only tested with small ZIMs obviously)
- ZIM might appear in _Opened_ view if it completed download.
- In _Opened_ view, clicking on the ZIM brings same right-column content as in _Categories_ view: with just the download button, no open one.
- Closing the app completely and re-opening allows _Opened_ view to reveal proper buttons and access the ZIM content.

**Comment by BPerlakiH** [comment] 2024-01-25 22:26
@rgaudin I double checked this. I see some discrepancies here.
Building from the main branch works fine.
Downloaded the last version from TestFlight (version 3.2, build 138), I assume this is the nightly you are referring to, and it is failing there.
When I looked under "developer.apple.com", the TestFlight build metadata shows that it was uploaded 28 November 2023:
<img width="236" alt="Screenshot 2024-01-25 at 23 24 56" src="https://github.com/kiwix/apple/assets/6784320/067dacc6-3443-4c52-b209-de92d46297be">

Under the Github CD job, I do see successes, but it seems to me that the upload part to TestFlight is skipped.
Maybe it's due to the matrix and the `if`s  on the build steps.

**Comment by rgaudin** [comment] 2024-01-26 09:20
https://download.kiwix.org/nightly/2024-01-22/kiwix-2024-01-22.dmg that's the one I used

**Comment by kelson42** [comment] 2024-02-06 19:54
> Under the Github CD job, I do see successes, but it seems to me that the upload part to TestFlight is skipped.

@BPerlakiH If this is confirmed by you and not handle within one of the PR/issue we have, please open a dedicated issue.

**Comment by kelson42** [comment] 2024-02-06 19:55
Basically it owrks for one of you and not for the other?! Something is fischy somewhere. @BPerlakiH Can you try with the nightly? Does that mean we have a problem specific to the nighlty, if the download feature works fine otherwise?

**Comment by BPerlakiH** [comment] 2024-02-07 09:39
@kelson42 @rgaudin I double checked it with the nightly, the download indeed is not working there as expected.
I will investigate it further, as it works on main branch, built locally.
it might be down to some permission that is treated differently, if it's not via TestFlight / AppStore.

**Comment by kelson42** [comment] 2024-02-07 10:00
@BPerlakiH Thx for your feedback. Please handle project tickets and 3.3.0 milestone in prio.

**Comment by BPerlakiH** [comment] 2024-02-09 12:04
Just double checked the TestFlight release 3.3.0, it has the same issue.

**Comment by BPerlakiH** [comment] 2024-02-18 22:04
@rgaudin I have spent quite an amount of time trying to track down this issue, but couldn't find anything that would cause this. I went back to main branch, and it is working now... So it was strange. I grabbed the app from TestFlight, that was working as well... I tracked even further... and nothing... 
I downloaded the app version you pointed at again, and it is working now as well... even stranger.
My current assumption is that it must be some corrupted local data, might be related to the language selection, I just fixed on the other PRs.
One thing is for sure, it's not the build that is causing it, might be either the server or local data outside of the application.
It will be worth to retest it, once we merge the other PRs.

**Comment by rgaudin** [comment] 2024-02-19 10:18
I've tested with today's nightly and it's the same.

I've cleared the container and with today's nightly it works fine.

I am worried about that many (most maybe?) users are stuck with this buggy behavior. They have no way to known that there's a fix, what the fix is and even if they did, removing the container requires `sudo`. We need to discuss a way forward.

**Comment by kelson42** [comment] 2024-02-19 11:22
We need to identify, what in the user configuration makes the app to fail to download properly.

**Comment by BPerlakiH** [comment] 2024-02-19 21:41
I think ultimately what we need to test is on a clean container, install the current AppStore version, and then install the latest TestFlight build. End users won't get access to our intermediate builds after all.

**Comment by BPerlakiH** [comment] 2024-02-22 22:26
I tested the above scenarios as part of  #663 .
Once that is merged, this can be re-tested via TestFlight.

**Comment by rgaudin** [comment] 2024-02-29 17:43
When installing current App Store version then installing testflight version, I am affected again.

**Comment by BPerlakiH** [comment] 2024-03-01 09:57
I used the following steps to get a clean environment:
Open Applications -> Move Kiwix to Trash
Empty Trash
from the command line run:
`rm -rf ~/Library/Containers/self.Kiwix`

**Comment by rgaudin** [comment] 2024-03-01 10:43
We still believe it might have to do with the intermediate testing builds. To make sure that's the case and to ensure genuine users are not affected, we will test the following scenarios, **all from a clean environment**:

## .app scenario

- Install from [`3.1.0` dmg](https://download.kiwix.org/release/kiwix-desktop-macos/kiwix-desktop-macos_3.1.0.dmg)
- Download from catalog
- Add local ZIM files

## app-store scenario

- Install `3.1` from [App Store](https://apps.apple.com/ml/app/kiwix/id997079563)
- Download from catalog
- Add local ZIM files


Both initial scenarios should be tested with updates:
- from nightly dmg
- from TestFlight build

That means four testing outcomes.

If all four outcomes are positive (no download issue), then I think we can safely close this and consider it only affects testers under certain conditions and not regular users.

**Comment by BPerlakiH** [comment] 2024-03-01 21:55
I tested all the above scenarios and it seems to be working with all those paths:
|FROM    |TO	|DOWNLOADING|
|---|---|---|
|.dmg	|.dmg	|✅|
|.dmg	|TestFlight	|✅|
|AppStore	|TestFlight	|✅|
|AppStore	|.dmg	|✅|

**Comment by rgaudin** [comment] 2024-03-04 13:02
Please find my [container folder](https://tmp.kiwix.org/ci/containers/self.Kiwix.tar).
With this container, the download issue can be reproduced. Please use it to find the root cause.

#680 might be related to it as well

**Comment by rgaudin** [comment] 2024-03-04 13:26
I confirm that I can get away of the bug by removing the container folder and have it back by expanding this tarfile.
Please use GNU tar (`brew install gnu-tar`) to expand (`cd  ~/Library/Containers/ ; gtar xf self.Kiwix.tar`)

**Comment by kelson42** [comment] 2024-03-05 12:06
@rgaudin Thank you@
@BPerlakiH Can you please try to reproduce the problem with the container dump? Once this is done, please identify which part creates the crash and share it here with us. We should then think a solution to deal with such scenarios.

**Comment by BPerlakiH** [comment] 2024-03-08 01:37
@kelson42 @rgaudin Finally, I have found the very root cause of this strange issue, please see the explanation and fix here: 
https://github.com/kiwix/apple/pull/686

**Closed** 2024-03-08 09:53 UTC
Labels: bug, macOS
