### ISSUE TITLE
"Clear recent Search" just crash

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#226] opened 2020-03-06 10:26 UTC

**Comment by automactic** [comment] 2020-03-08 01:06
I don't know what to tell you. UIKit is asking for a cell of the collection view when the collection view goes off screen for some reason in iOS 13. (And that is the root cause of this problem)

**Comment by automactic** [comment] 2020-03-08 01:06
Also nit: I would really appreciate it if you could provide at least a bit of detail.

**Comment by automactic** [comment] 2020-03-08 20:20
@kelson42 this issue should have been fixed in build 37, please check

**Comment by automactic** [comment] 2020-03-19 14:58
This issue has been fixed in https://github.com/kiwix/apple/commit/0bc61023ee7ec27e67a4a1f48aa8bc566758cf4e. Please re-open if necessary

**Closed by automactic** 2020-03-19 14:58 UTC
Labels: bug, iOS
