### ISSUE TITLE
Open Zimit files in iOS/ macOS app

### ISSUE THREAD

**Issue by BenjaminJMueller** [kiwix/apple#488] opened 2023-02-26 18:33 UTC
Zimit files using ServiceWorker are still not supported on all the apple apps. I am aware that I could use the PWA but it would be so great, if that support for the native iOS/ macOS is coming soon!
How is the status on this issue?

**Comment by kelson42** [comment] 2023-02-27 05:50
Duplicate of #341

**Closed by kelson42** 2023-02-27 05:50 UTC
