### ISSUE TITLE
Wikipedia download stucks

### ISSUE THREAD

**Issue by Maxus79** [kiwix/apple#451] opened 2022-07-04 00:54 UTC
I was able to download any content in Kiwix iOS app except Wikipedia itself - each time it starts normally, but then stucks on or around 100%. I've tried a dozen times already. iOS 15.5. iPhone 13 mini

**Comment by kelson42** [comment] 2022-07-04 07:11
@Maxus79 What is your version of Kiwix?

**Comment by kelson42** [comment] 2022-07-05 07:46
Duplicate of #452

**Closed by kelson42** 2022-07-05 07:46 UTC
Labels: bug, iOS
