### ISSUE TITLE
Sotoki ZIM files links completly broken

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#227] opened 2020-03-07 15:42 UTC
Steps:
* Download https://download.kiwix.org/zim/stack_exchange/3dprinting.stackexchange.com_en_all_2020-01.zim
* Open the home page
* Click on the first question

I get:
* Nothing happens

I want:
* The first question loaded

Works fine on kiwix-serve

**Comment by automactic** [comment] 2020-03-08 01:42
Here is what I found:
```
kiwix::Entry entry = reader->getEntryFromPath([contentURL cStringUsingEncoding:NSUTF8StringEncoding]);
kiwix::size_type size = entry.getSize();
NSLog([NSString stringWithFormat:@"value is: %lld", size]);
```

When `contentURL=@"/A/index.html"`, I got `value is: 25534`
When `contentURL=@"/A/question/11/how-do-i-give-3d-printed-parts-in-pla-a-shiny-smooth-finish.html"`, I got `value is: 3`

**Comment by automactic** [comment] 2020-03-08 01:47
I am going to rebuilding libkiwix and try again

**Comment by automactic** [comment] 2020-03-08 03:19
rebuild libkiwix, I still get the same result

**Comment by kelson42** [comment] 2020-03-08 03:21
@automactic I think we have changed recently a type of the content length to support big content.I would secure that on your side your variable typing is coherent with the one in the libkiwix.

**Comment by automactic** [comment] 2020-03-08 03:29
Note that I am directly print out C++ variables there.

Based on the header file I got `kiwix::size_type` is `uint64_t`. But even if I changed my logging code to `NSLog([NSString stringWithFormat:@"value is: %llu", size]);`, I still got `value is: 3`

**Comment by automactic** [comment] 2020-03-08 03:45
Also, I don't know why but the url the webview loads for the first article in main page is different.  On iOS, it is `/A/question/11.html`, on macOS it is `/A/question/11/how-do-i-give-3d-printed-parts-in-pla-a-shiny-smooth-finish.html`

**Comment by kelson42** [comment] 2020-03-08 03:56
@automactic Might that be that you get lost in redirect handling?

**Comment by automactic** [comment] 2020-03-08 04:42
These URL I am listing above are the url the app's custom URL scheme handler are asked to load by iOS / macOS's webview. 

Also, FWIW the iOS and macOS app does not deal with redirection at all. And I don't think it should. The apps' jobs is to loyally pass the web view's web request to libkiwix and transmit the data back to the system webview. 

Also also, the custom URL scheme data loading code for iOS and macOS are shared. And this zim file works fine on iOS. So I wouldn't rule out there there some macOS specific webview issue. I wouldn't be surprised, given how disastrous macOS Catalina has been since it was released.

**Comment by automactic** [comment] 2020-03-08 04:48
> the iOS and macOS app does not deal with redirection at all

@kelson42 If you don't agree with this statement of mine, could you please tell me very specifically how I should handle redirection?

**Comment by kelson42** [comment] 2020-03-08 04:53
This is the problem. I thought like you in the past. The problem is that this is wrong. One important reason is that there is a strong relationship between the URL loaded and how relative URLs are made in the HTML document. As a consequence, if a redirect target URL is not as a same level of depth, then this will brake all links because the webview has no clue it has been redirected to an other URL.

**Comment by kelson42** [comment] 2020-03-08 12:53
BTW, this works fine on iOS

**Comment by automactic** [comment] 2020-03-08 20:13
Again, please be very specific about how the application should handle redirection. The two most important questions for you are: 1) which function in libkiwix can I use to check if a url should be redirected to something else, 2) how to retrieve the redirected url given a url. Without getting answers on these two questions, there is no way for users of libkiwix (i.e. reader app developers) to know how redirection should be implemented.

**Comment by automactic** [comment] 2020-03-08 20:15
> BTW, this works fine on iOS

This, could be an indication that this problem is more than redirection / not redirection. Because the implementation on how contents are loaded are shared among the two systems

**Comment by kelson42** [comment] 2020-03-08 20:16
@automactic First of all I did not say this is a redirect, just this might be. Then, I guess how to handle it because the iOS can handle it properly. For the rest please have a look with @mgautierfr, younprobably already know the libkiwix better than I do.

**Comment by mgautierfr** [comment] 2020-03-25 14:30
```
kiwix::Entry entry = reader->getEntryFromPath([contentURL cStringUsingEncoding:NSUTF8StringEncoding]);
kiwix::size_type size = entry.getSize();
NSLog([NSString stringWithFormat:@"value is: %lld", size]);
```

Please test if the entry is a redirection with `entry.isRedirect()`.
If it is, you can get the entry on which the entry is pointing using `entry.getRedirectEntry()` (If it is not a redirect entry, it will throw an exception)
You can always use `entry.getFinalEntry()` witch will return the entry itself or the entry at the end of the redirection chain.

```
kiwix::Entry entry = reader->getEntryFromPath([contentURL cStringUsingEncoding:NSUTF8StringEncoding]);
entry = entry.getFinalEntry();
kiwix::size_type size = entry.getSize();
NSLog([NSString stringWithFormat:@"value is: %lld", size]);
```

If you only care about the content the simpler is to always use `getFinalEntry()`.
But, as the url of the entry and the finalEntry can be different (and so break relative url in the content), you probably have to check if it is
a redirection and redirect the "view" to the finalEntry/url.

**Comment by kelson42** [comment] 2020-03-25 14:31
@mgautierfr Please fix it if you can, this is really urgent now.

**Comment by mgautierfr** [comment] 2020-03-25 14:37
If is it confirmed, it is a misuse of the API. This have to be fix in the apple code.

**Comment by kelson42** [comment] 2020-03-25 14:42
@mgautierfr Sorry got confused with the link problem which is really urgent to fix on Kiwix-Desktop and impacting Sotoki. See https://github.com/kiwix/kiwix-desktop/issues/384

**Comment by mgautierfr** [comment] 2020-03-25 15:08
Yes.

For you info @automactic, the fix for kiwix-desktop (https://github.com/kiwix/kiwix-desktop/pull/390) is probably what you need to do on apple side.

**Comment by kelson42** [comment] 2020-07-05 06:25
I don’t know how, but this bug has been fixed. It works now.

**Comment by automactic** [comment] 2020-08-15 15:50
I can no longer reproduce this issue on the latest 3d printing stack exchange zim file (3dprinting.stackexchange.com_en_all_2020-04.zim).

But I have indeed realize I already perform hack / patches to the loading logic on the iOS app similar to https://github.com/kiwix/kiwix-desktop/pull/390, so I just copy and pasted the same logic to the macOS app side in #306. I am marking this as done. Happy to investigate more if the same issue occurs again

**Closed by automactic** 2020-08-15 15:50 UTC
Labels: bug, macOS
