### ISSUE TITLE
The app can’t search some zim files possibly after 13.5 update

### ISSUE THREAD

**Issue by Shady-3** [kiwix/apple#262] opened 2020-05-25 12:10 UTC
I use iPad 2018 with iPadOS 13.5
I have wiktionary_en_nopic_2017_08.zim and Arabic Wikipedia (wikipedia_ar_all.zim from 2019) both downloaded. When I select the wiktionary and try to search it tells me that there is no search results but the Arabic Wikipedia works fine.
I believe this started to happen when I updated to latest iOS version yesterday. It worked fine before the update. I tried restarting the device and reinstalling the app but to no avail.

**Comment by Popolechien** [comment] 2020-05-26 08:48
Piling up on this to say I received multiple similar reports with failure to retrieve zims and search within them (zims are Wikipedia in Spanish, German and English).

**Comment by automactic** [comment] 2020-05-31 22:19
@Shady-3 Could you try a newer version of the wiktionary file? 

If it still does not solve the issue, could you provide me with the name of the newer wiktionary file and the search term you used? (I would appreciate it if you could find an English example, since I don't speak Arabic)

**Comment by automactic** [comment] 2020-06-09 13:54
There has been no new feedback form the reporter of the issue in 9 days. So I am going to close this as a duplicate of #265

**Closed by automactic** 2020-06-09 13:54 UTC
Labels: bug
