### ISSUE TITLE
iOS app immediately crashes on startup [1.15.3 / iPadOS 14.7.1]

### ISSUE THREAD

**Issue by SimNico** [kiwix/apple#431] opened 2021-12-19 18:01 UTC
I tried reinstalling the app and restarting the device, still won't launch.

**Comment by Raupinger** [comment] 2021-12-22 10:45
Same here with iPad os 14.4

**Comment by Bakr-Ali** [comment] 2021-12-27 05:11
Same issue on iPadOS 14.4 too. There are several similar reports on the App Store latest reviews.

**Comment by Bakr-Ali** [comment] 2021-12-27 05:13
Same issue on iPadOS 14.4 too. There are several similar reports on the App Store latest reviews.
@automactic @kelson42  could you please look into this issue?

**Comment by Raupinger** [comment] 2021-12-27 20:48
Ive upgraded to ios 14 now and can confirm that the app now works fine. But there's plenty of reasons one wouldn't want to or be able to do that

**Comment by SimNico** [comment] 2021-12-28 10:39
In my case I'm using the iPad for work and I'm unable to upgrade to iOS 15 due to some professional apps not being compatible yet.

**Comment by automactic** [comment] 2022-01-13 14:26
Hey, I will take a look at this over the weekend

**Comment by ifuchs** [comment] 2022-01-15 13:03
App crashes at launch on ipadOS 15.3.

**Comment by automactic** [comment] 2022-01-19 00:37
@SimNico @Bakr-Ali I cannot reproduce this on iOS 14 simulator, nor do I see any elevated crash rate on iOS 14. Anyway, I have made a new build with some 3rd party library updates. Could you try signing up through [TestFlight](https://testflight.apple.com/join/pKozwnSU) and let me know if the new build work for you?

@ifuchs iPadOS 15.3 is not released yet

**Comment by ifuchs** [comment] 2022-01-19 03:11
Not sure why you say that. I am running iPadOs 15.3.

**Comment by Raupinger** [comment] 2022-01-19 08:19
The latest public version of iPadOS is 15.2.1

**Comment by ifuchs** [comment] 2022-01-19 13:48
Quite so. I have 2 iPads, one running 15.2.1 and one running the latest
beta of 15.3. The latter is the one crashing on startup.

**Comment by automactic** [comment] 2022-01-19 14:04
@ifuchs anyway, please try the new build via TestFlight and let me know how it goes

**Comment by SimNico** [comment] 2022-01-19 14:08
> @ifuchs anyway, please try the new build via TestFlight and let me know how it goes

You need to provide us with an invitation code for this afaik.

**Comment by automactic** [comment] 2022-01-19 16:17
I included a public sign up link to TestFlight in one of my earlier comment. Here is the link again: https://testflight.apple.com/join/pKozwnSU

**Comment by SimNico** [comment] 2022-01-19 17:07
It does seem to work. No crash on startup and I was able to download and use a random zim.

**Comment by automactic** [comment] 2022-01-20 16:29
@SimNico A new version will be released soon on App Store, it will be using the same build as the one you are testing

**Comment by automactic** [comment] 2022-01-20 16:30
> It works on 15.2.1, but it crashes on the Public beta of ios 15.3.

@ifuchs could you clarify what does "it" mean? Is it the TestFlight build or the current App Store build?

**Comment by ifuchs** [comment] 2022-01-20 16:32
Both the App Store and the Test flight build crash under the ipados 15.3 beta

**Comment by SimNico** [comment] 2022-01-20 16:34
Great !

**Comment by Bakr-Ali** [comment] 2022-01-20 16:44
Thanks ChrisLi! Latest TestFlight version works on iPadOS 14.3.

**Comment by kelson42** [comment] 2022-05-12 06:44
@Bakr-Ali @ifuchs @SimNico @Raupinger Does one of you still suffer of this problem with latest 1.15.5?

**Comment by SimNico** [comment] 2022-05-12 09:15
I've had crashes when typing in the search bar but that's an issue that was anterior to this one, so I can confirm no more crashes on app launch.

**Comment by kelson42** [comment] 2022-05-12 10:35
Closing the ticket. If this scenario happens again with 1.15.5+, please open a new ticket.

**Comment by ifuchs** [comment] 2022-05-12 12:15
Kiwix crashes on startup under iOS 15.4.1.

**Comment by kelson42** [comment] 2022-11-09 13:32
@ifuchs Do you still have the problem with latest testflight version https://testflight.apple.com/join/pKozwnSU ?

**Comment by ifuchs** [comment] 2022-11-09 17:22
Yes, it continues to crash immediately on start up. Now running iPadOS 15.7.1

**Comment by kelson42** [comment] 2022-11-09 18:55
@ifuchs Thx for the quick testing, have you sent the report? What have you written in it (so we can identify it)?

**Comment by ifuchs** [comment] 2022-11-09 19:41
My email address is in the report and the only information I added was that
it crashes on startup.

**Comment by kelson42** [comment] 2023-11-25 13:27
Puzzled about what to do with this issue considering we fail to reporudce it… or does that work better with version 3.2.0?

**Comment by kelson42** [comment] 2023-11-25 13:37
I close the ticket because it is so old, but if anybody has still or again this scenario, I would very welcome a new issue so we can restart from there.

**Closed by kelson42** 2023-11-25 13:37 UTC
Labels: question, iOS
