### ISSUE TITLE
MDN is missing on iOS and Mac

### ISSUE THREAD

**Issue by stephane-archer** [kiwix/apple#490] opened 2023-03-22 20:14 UTC
in the following website https://library.kiwix.org/?lang=&q=MDN I can see that MDN website is available to download but on my iPhone or Mac I can’t find it when looking in the “catalog”.

If I download it from the website and then import it into the app I can see the warning "Zim files requiring service workers are not supported" so this might be the reason.

**Comment by rgaudin** [comment] 2023-03-28 08:49
I don't think it's a bug. #362 clearly says “hide” in the title so it's not shown. I believe #362 should be closed. FYI should you manually add a SW ZIM, there is a warning that is shown (as reported here).

https://github.com/kiwix/apple/blob/d7fc77792a7fd72785208dd4e8c339125915fc8d/SwiftUI/Library/ZimFilesCategories.swift#L48-L60

**Comment by stephane-archer** [comment] 2023-03-28 12:49
I'm not sure I understand what is happening, from my understanding MDN is hidden on iOS because it requires Service Workers and iOS doesn't support this feature. Am I correct?

**Comment by rgaudin** [comment] 2023-03-28 13:04
Yes, exactly

**Comment by kelson42** [comment] 2023-03-28 15:58
Duplicate of #341

**Closed by kelson42** 2023-03-28 15:58 UTC
Labels: bug, macOS, iOS
