### ISSUE TITLE
Kiwix MacOS always crash by trying to open an non-existing article

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#157] opened 2019-06-29 07:26 UTC
Steps:
1 - Download http://tmp.kiwix.org/wikivoyage_en_all_novid_2019-06.zim
2 - Open main page
3 - Click on "Europe"

You get:
1 - Application quits

You should get:
1 - An empty page or an error

Remark
Link "Europe" points to an non-existing article, this is the root of the bug probably...

**Comment by Jaifroid** [comment] 2019-07-15 10:14
[This is a copy of https://github.com/openzim/mwoffliner/issues/852#issuecomment-511344925] This issue probably is related to the fact that the hyperlinks on the landing page of `wikivoyage_en_all_novid_2019-06.zim` are incorrect. The landing page's URL is: 

`Wikivoyage%3AOffline_reader_Expedition/Home_page`

(note the forward slash). However, hyperlinks on the page are:

`<a title="Europe" href="Europe">Europe</a>`

That's clearly incorrect, as the href should be `../Europe`. This should have been fixed in mwoffliner https://github.com/kiwix/kiwix-js/pull/498. I'm not sure #157 should "fix" what is an error in the ZIM.

**Comment by jhbiggs** [comment] 2019-08-25 19:35
Is this issue current?  Do I need a paid Apple Developer license to build this app via Xcode? My first attempt failed because of a missing provisioning profile for WikiMed.

**Comment by Jaifroid** [comment] 2019-08-26 08:59
@jhbiggs I would say this issue is still current until https://github.com/openzim/mwoffliner/issues/726 is fully resolved. I don't know about your other questions.

**Comment by kelson42** [comment] 2019-08-26 13:30
@jhbiggs Yes, I confirm.

**Comment by automactic** [comment] 2020-08-15 15:53
@kelson42 Do you happen to have a zim file available to test this issue? If not, I am gonna close this as unable to reproduce

**Comment by kelson42** [comment] 2020-08-15 16:03
@automactic It seems to not crash anymore indeed. That said, no info/erro is printed either.

**Comment by automactic** [comment] 2020-08-15 18:31
> That said, no info/erro is printed either.

You mean when click on an article that does not exist? Do you have an example zim file that could be used as test? I have recently added a alert for this scenario on iOS could certainly do the same for macOS

**Comment by kelson42** [comment] 2020-08-16 13:26
@automactic the current edutech fr has a lot of them.

**Comment by automactic** [comment] 2020-08-16 16:03
added alert in #308 

<img width="1092" alt="Screen Shot 2020-08-16 at 12 01 36 PM" src="https://user-images.githubusercontent.com/8294252/90338533-3f779700-dfb8-11ea-9a98-02acb3498a42.png">

**Closed by automactic** 2020-08-16 16:03 UTC
Labels: bug, good first issue, macOS
