### ISSUE TITLE
zim file open incorrectly on iOS 9 and 11

### ISSUE THREAD

**Issue by Popolechien** [kiwix/apple#73] opened 2017-10-16 08:50 UTC
I'm copy-pasting the exchange I had with the user (+screenshot):

"I have tried on an iPad 2 running 9.3.5 (downloaded with jailbreak running) and I cannot open the zim file I downloaded from the app.
It did initially open but it looked like it was the css code , I did reboot into 9.35 no jailbreak and it simply does not open.  Would this be because I am using a 32 bit device perhaps ? I have not attempted this on an iPhone 6 with current iOS 11 but will try later I'm sure.  It will not download any other files and just crashes although I have several gb free space."

And then...

"Well I transferred the Wikipedia zim file to an iPhone 6 updated to the new iOS and see the same as what I saw once on the iPad ...."
![bug](https://user-images.githubusercontent.com/21675885/31603151-8833e662-b25f-11e7-9b01-5acfa185de33.JPG)

**Comment by automactic** [comment] 2017-10-16 13:49
Which zim file are you using?

**Comment by Popolechien** [comment] 2017-10-16 14:06
I've asked the gentleman.

**Comment by automactic** [comment] 2017-10-16 20:08
Without knowing the name of the specific zim file in question, we cannot further investigate. Also please try re-download the latest version of Kiwix from App Store on the device running iOS 11.

**Comment by Popolechien** [comment] 2017-10-17 17:04
File name is wikipedia_en_wp1-0.8_orig_2010-12.zim
(waiting for feedback from re-download)

**Comment by Popolechien** [comment] 2017-10-18 06:30
"Both devices have reinstalled.  
On iPad 2,2 iOS 9.35 won’t open files but downloaded them. 
On iPhone 6 iOS 11. Has downloaded three different ones and all worked. ( I’ll note the “browse” dictionary by letter did not work but that’s about as far as I went after downloading the three. )"

**Comment by automactic** [comment] 2018-02-02 22:03
This is likely an zim file issue. Closed due to lack of activity.

**Comment by kelson42** [comment] 2018-02-03 19:08
@automactic Can you confirm it works for you?

**Comment by automactic** [comment] 2018-02-05 19:13
This issue is not easy to be reproduced for me, since I have no idea where I should get the zim in question (wikipedia_en_wp1-0.8_orig_2010-12.zim)

Also the user mentioned:
> On iPhone 6 iOS 11. Has downloaded three different ones and all worked.

Also 9.3.5 is no longer supported. 

I don't see a point of keeping this open.

**Comment by kelson42** [comment] 2018-02-05 19:15
@automactic We need at least to verify the newest version of Kiwix does not have the problem. The file is available here https://download.kiwix.org/zim/wikipedia/wikipedia_en_wp1-0.8_orig_2010-12.zim

**Comment by kelson42** [comment] 2018-02-11 20:54
I confirme that the pb is still there with 1.9

**Comment by automactic** [comment] 2018-02-13 16:34
I did some investigation. I found this problem is caused by string encoding. 

The GET request of main page of wikipedia_en_wp1-0.8_orig_2010-12.zim is as follows:
URL: kiwix://4dd18dea-9afd-080a-50c6-8d62072f5675/A/Main%20Page.html
MIME: text/html; charset=utf-8
Data Decoded as UTF8: 
[data.txt](https://github.com/kiwix/apple/files/1720725/data.txt)

**Comment by kelson42** [comment] 2018-02-13 16:37
@automactic What is the exact problem? What should be delivered instead of that?

**Comment by automactic** [comment] 2018-02-13 18:44
@kelson42 I do not know

**Comment by automactic** [comment] 2018-02-13 18:50
@kelson42 Another interesting thing I found is, pretty much in all other zim files, the mime of a html would be `text/html`, not containing the charset part. So I forced the content type to also be just `text/html` for all htmls in the problematic zim file. The page loads!

**Comment by kelson42** [comment] 2018-02-13 19:22
@automactic I'm not surprised about the problem with the mime-type. If it works well with your approach, then this was probably the best thing to do :) Thx. We can close the ticket then I think.

**Comment by automactic** [comment] 2018-02-13 19:25
Are you saying I should always replace `text/html; charset=utf-8` with `text/html` in the mime? I don't think we should.

**Comment by automactic** [comment] 2018-02-13 19:53
Mmm, yes. This does seems to be an iOS only issue. 

I have also tested setting all html mime as `text/html; charset=utf-8` in other zim files, all loading failed and is showing the plain HTML code. 🤦🏻‍♂️

Will add the fix in the next beta.

**Comment by kelson42** [comment] 2018-02-14 16:57
As far I can see this bug is fixed in 1.9 (7) 👍

**Comment by kelson42** [comment] 2018-02-25 12:31
@automactic Sorry, but the bug seems to have reappeared (both for ICS and Wikipedia 0.8 file).

**Comment by automactic** [comment] 2018-02-26 16:45
OK, I think I have found a better fix for this issue. Instead of using the designated initializer of `URLResponse`, which is a more convenient way of assemble a response, I now use `HTTPURLResponse`, a subclass of `URLResponse `, to directly set headers, body, etc.

**Comment by kelson42** [comment] 2018-02-27 19:19
Works again

**Closed by kelson42** 2018-02-27 19:19 UTC
