### ISSUE TITLE
Search crashes on first letter typed on Ventura

### ISSUE THREAD

**Issue by keyle** [kiwix/apple#471] opened 2022-10-29 02:24 UTC
MacOS 13.0 (Ventura) on Intel Mac Mini 2018+ (unsure about previous OS versions).

Steps to reproduce:

- download `ifixit_en_all_2022-10.zim` from here https://ftp.fau.de/kiwix/zim/ifixit/ 
- open the zim file in kiwix
- type `s` in the search bar 
- application disappears (crash - no message).

Tested on both dmg version and app store version.

Obviously a big problem seeing search is the main usage vector of this application type.

Work around: none :(

**Comment by kelson42** [comment] 2022-10-30 09:39
To me a duplicate of #444. But already fixed in next release.

**Comment by keyle** [comment] 2022-10-30 10:06
any ETA on that next release? I'm worried if it's the case and it's broken on Monterey since mid-April and the bot flagged the issue as "stale".

**Comment by kelson42** [comment] 2022-10-30 10:08
No ETA, but we are running final tests and this is already pretty release ready.

**Comment by keyle** [comment] 2022-10-30 10:34
Great to hear, thanks!

**Comment by rgaudin** [comment] 2022-10-30 10:39
You can use https://github.com/technusm1/kiwings in the mean time

**Comment by keyle** [comment] 2022-10-30 11:29
Appreciated. Installed, works well - thanks!

**Closed** 2022-10-30 12:44 UTC
Labels: bug, macOS
