### ISSUE TITLE
Systematic crash by unlinking content

### ISSUE THREAD

**Issue by kelson42** [kiwix/apple#329] opened 2020-10-22 10:50 UTC

**Comment by automactic** [comment] 2020-11-24 03:05
Hi did you add the file? What is the iOS version?

I cannot reproduce by tapping the "plus" button inside the library, select a file and select "open in place". Also I am on iOS 14.2

**Comment by kelson42** [comment] 2020-11-24 05:21
I add files with the plus button. I use ipados 14.2. I have uploaded many crash reports, do you see them?

**Comment by kelson42** [comment] 2020-12-06 10:27
@automactic The bug is not visible anymore in 1.13.7, but I guess you want to have a proper fix?

**Comment by automactic** [comment] 2020-12-26 14:03
@kelson42 Yes, I do want a proper fix for this

**Closed** 2020-12-26 14:44 UTC
Labels: enhancement, good first issue, iOS
