### ISSUE TITLE
No way to search text WITHIN an article?

### ISSUE THREAD

**Issue by RogerRamjet-AJ** [kiwix/apple#504] opened 2023-07-03 07:28 UTC
I'm using the latest Kiwix on an Apple MacBook Air M1.

I'm using the content file for Wikipedia (max).

Once I've found an article, I can see no way of searching the text within that article. I can't find any typical keyboard shortcut (e.g. command-F) or anything in the menu. The Help menu item says no help is available.

Sorry if I've missed something obvious, but if there is indeed currently no way of searching text in an article, could this be added as a feature request?

The absence of this feature is making what could be the best information-finding tool into one of the worst - having to read an entire article to find one item of interest.

**Comment by dustinfreeman** [comment] 2023-09-30 18:21
I agree, this request seems the same as this old unaddressed issue #79

**Comment by nk9** [comment] 2023-11-03 22:28
This is the number one issue affecting my use of Kiwix. I am almost always looking for some information which isn't in the article's summary.

Especially if this feature exists on the Android app, I'd love it if this could be prioritized on Mac/iOS.

**Comment by kelson42** [comment] 2023-11-04 05:34
Duplicate of #79

**Closed** 2023-11-04 05:35 UTC
Labels: question, macOS, duplicate
